// Code generated by "go-enum -type=BucketRegion -linecomment"; DO NOT EDIT.

// Install go-enum by `go get install github.com/searKing/golang/tools/go-enum`
package domain

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BucketRegionInvalid-0]
	_ = x[BucketRegionAPSouthEast1-1]
	_ = x[BucketRegionAPSouthEast2-2]
	_ = x[BucketRegionEUCentral1-3]
	_ = x[BucketRegionEUWest2-4]
	_ = x[BucketRegionUSEast1-5]
	_ = x[BucketRegionUSWest1-6]
}

const _BucketRegion_name = "invalidap-southeast-1ap-southeast-2eu-central-1eu-west-2us-east-1us-west-1"

var _BucketRegion_index = [...]uint8{0, 7, 21, 35, 47, 56, 65, 74}

func _() {
	var _nil_BucketRegion_value = func() (val BucketRegion) { return }()

	// An "cannot convert BucketRegion literal (type BucketRegion) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_BucketRegion_value
}

func (i BucketRegion) String() string {
	if i < 0 || i >= BucketRegion(len(_BucketRegion_index)-1) {
		return "BucketRegion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BucketRegion_name[_BucketRegion_index[i]:_BucketRegion_index[i+1]]
}

// New returns a pointer to a new addr filled with the BucketRegion value passed in.
func (i BucketRegion) New() *BucketRegion {
	clone := i
	return &clone
}

var _BucketRegion_values = []BucketRegion{0, 1, 2, 3, 4, 5, 6}

var _BucketRegion_name_to_values = map[string]BucketRegion{
	_BucketRegion_name[0:7]:   0,
	_BucketRegion_name[7:21]:  1,
	_BucketRegion_name[21:35]: 2,
	_BucketRegion_name[35:47]: 3,
	_BucketRegion_name[47:56]: 4,
	_BucketRegion_name[56:65]: 5,
	_BucketRegion_name[65:74]: 6,
}

// ParseBucketRegionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseBucketRegionString(s string) (BucketRegion, error) {
	if val, ok := _BucketRegion_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BucketRegion values", s)
}

// BucketRegionValues returns all values of the enum
func BucketRegionValues() []BucketRegion {
	return _BucketRegion_values
}

// IsABucketRegion returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BucketRegion) Registered() bool {
	for _, v := range _BucketRegion_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_BucketRegion_value = func() (val BucketRegion) { return }()

	// An "cannot convert BucketRegion literal (type BucketRegion) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_BucketRegion_value

	// An "cannot convert BucketRegion literal (type BucketRegion) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_BucketRegion_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for BucketRegion
func (i BucketRegion) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for BucketRegion
func (i *BucketRegion) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseBucketRegionString(string(data))
	return err
}

func _() {
	var _nil_BucketRegion_value = func() (val BucketRegion) { return }()

	// An "cannot convert BucketRegion literal (type BucketRegion) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_BucketRegion_value

	// An "cannot convert BucketRegion literal (type BucketRegion) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_BucketRegion_value
}

// MarshalJSON implements the json.Marshaler interface for BucketRegion
func (i BucketRegion) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BucketRegion
func (i *BucketRegion) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BucketRegion should be a string, got %s", data)
	}

	var err error
	*i, err = ParseBucketRegionString(s)
	return err
}

func _() {
	var _nil_BucketRegion_value = func() (val BucketRegion) { return }()

	// An "cannot convert BucketRegion literal (type BucketRegion) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_BucketRegion_value

	// An "cannot convert BucketRegion literal (type BucketRegion) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_BucketRegion_value
}

// MarshalText implements the encoding.TextMarshaler interface for BucketRegion
func (i BucketRegion) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for BucketRegion
func (i *BucketRegion) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseBucketRegionString(string(text))
	return err
}

//func _() {
//	var _nil_BucketRegion_value = func() (val BucketRegion) { return }()
//
//	// An "cannot convert BucketRegion literal (type BucketRegion) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_BucketRegion_value
//
//	// An "cannot convert BucketRegion literal (type BucketRegion) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_BucketRegion_value
//}

// MarshalYAML implements a YAML Marshaler for BucketRegion
func (i BucketRegion) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for BucketRegion
func (i *BucketRegion) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseBucketRegionString(s)
	return err
}

func _() {
	var _nil_BucketRegion_value = func() (val BucketRegion) { return }()

	// An "cannot convert BucketRegion literal (type BucketRegion) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_BucketRegion_value

	// An "cannot convert BucketRegion literal (type BucketRegion) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_BucketRegion_value
}

func (i BucketRegion) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *BucketRegion) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseBucketRegionString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// BucketRegionSliceContains reports whether sunEnums is within enums.
func BucketRegionSliceContains(enums []BucketRegion, sunEnums ...BucketRegion) bool {
	var seenEnums = map[BucketRegion]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// BucketRegionSliceContainsAny reports whether any sunEnum is within enums.
func BucketRegionSliceContainsAny(enums []BucketRegion, sunEnums ...BucketRegion) bool {
	var seenEnums = map[BucketRegion]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
